### ISSUE TITLE
Freeze DAE weights after training in The-Kaggle-Workbook/chapter_01 /workbook-dae.ipynb

### ISSUE THREAD

**Issue by jaydeepthik** [PacktPublishing/The-Kaggle-Workbook#1]
The DAE weights after training in (https://github.com/PacktPublishing/The-Kaggle-Workbook/tree/main/chapter_01)
 /workbook-dae.ipynb does not seem to be frozen for training the final NN.

**Comment by lmassaron** [comment]
That's a good observation, Jaydeep. I think it can be solved in this way:

```
def dnn_model(dae, units=[4500, 1000, 1000], 
            input_dropout=0.1, dropout=0.5,
            regL2=0.05,
            activation='relu'):

    for layer in dae.layers:
        layer.trainable = False
    
    inputs = dae.get_layer("code_2").output
    ...
```

I will make the appropriate tests and update the code and the book, thank you a lot for your feedback.

**Comment by jaydeepthik** [comment]
Thanks!
